import Head from "next/head";
import Link from "next/link";
import Articles from "../components/Articles/Articles";
import Banner from "../components/Banner/Banner";
import Footer from "../components/Footer/Footer";
import Subscribe from "../components/Subscribe/Subscribe";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tailwind CSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner />
        <Articles />
        <Subscribe />
        <Footer />
      </main>
    </div>
  );
}
